### ISSUE TITLE
Chats fixed title

### ISSUE THREAD

**Issue by ArtCrafter2999** [SparkChats/API#107]
Endpoint `Get api/private-chats` returns list of private chats like this:
```json
[
    {
        "id": "6516c139f14ce9a377267609",
        "image": "https://kkn.chnu.edu.ua/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/partials/images/default-group.png",
        "title": "Me and the boys",
        "subtitle": "4 members"
    },
    {
        "id": "651c02e90e17e337f8eeb4be",
        "image": null,
        "title": "grabtot2, grabtot3, Grabtot",
        "subtitle": "4 members"
    }
]
```
however, when I create a chat I try to instantaneously `get api/private-chats/{id}` and get this result:

```json
{
    "ownerId": "8422edbb-83ac-4936-842c-47a9574fc063",
    "image": null,
    "title": null,
    "id": "651d3696ba58b26c829a4cdf",
    "profiles": [
        "3ec50595-caf4-4f95-bffb-8717476737ae",
        "9d39012e-56c6-45c7-b9c9-327ce35cc6b7",
        "cb53432f-e7cb-49c3-af2f-5a5d00f4835d",
        "8422edbb-83ac-4936-842c-47a9574fc063"
    ]
}
```
It is obvious that I haven't set the title yet, but I already needed it for showing the chat, or it would appear like this:
![image](https://github.com/SparkChats/API/assets/92592800/40e5978b-8bd7-4f0b-be28-7f99d49c66ec)
The same goes for chat members who just received notify about a new chat.
I need to receive `title` field in format `"grabtot2, grabtot3, Grabtot"` even if there is no title also for  `get api/private-chats/{id}` and `NotifyPrivateChatSavedQuery`

**Comment by Grabtot** [comment]
I don't understand. explain in more details
