### ISSUE TITLE
Find Personal Chat from other user

### ISSUE THREAD

**Issue by ArtCrafter2999** [SparkChats/API#96]
In relationships there is the button:
![image](https://github.com/SparkChats/API/assets/92592800/474b14fe-3970-442e-b310-7dfa9a14caf5)
![image](https://github.com/SparkChats/API/assets/92592800/d429c857-ea4a-455c-923d-30aa86e28a2f)

Which opens the personal chat with the person.
So I want to somehow get ChatId from Realationship

**Comment by Grabtot** [comment]
I'll add this enpdoid for you
```http
GET api/private-chats?userId=guid
```
